apiVersion: v1
kind: Service
metadata:
  name: strimzi-console-server
  labels:
    name: strimzi-console-server
    app: strimzi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
    name: strimzi-console-server