apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: my-kafka-source
spec:
  image: quay.io/redhatdemo/kafka-src
  args: 
    - '--bootstrap=demo2019-kafka-bootstrap.strimzi-demo.svc.cluster.local:9092'
    - '--topic=data-filtered'
    - '--groupId=foobar'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: message-dumper