apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sensorstream-raw-service
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/maxScale: "100"
            autoscaling.knative.dev/target: "1"
        spec:
          container:
            image: docker.io/bbrowning/autoscale-8e086451fa21a3d715bdd62a0086ac55
            resources:
              requests:
                cpu: 25m
