apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-console-server
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-console-server
    spec:
      serviceAccountName: strimzi-console-server
      containers:
      - name: strimzi-console-server
        image: docker.io/ppatierno/console-server:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 8080