apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-console
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-console
    spec:
      containers:
      - name: strimzi-console
        image: quay.io/redhatdemo/console-pages:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 8888