apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: strimzi-console
  labels:
    app: strimzi
subjects:
- kind: ServiceAccount
  name: strimzi-console
  namespace: myproject
roleRef:
  kind: ClusterRole
  name: strimzi-admin
  apiGroup: rbac.authorization.k8s.io