apiVersion: v1
kind: Service
metadata:
  name: strimzi-console
  labels:
    name: strimzi-console
    app: strimzi
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: http
  selector:
    name: strimzi-console